export const CAREERS = [
  {
    position: 'Senior Full Stack Engineer',
    company: 'Gamma',
    logo: '/images/careers/Gamma.png',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Apr 2022',
    end_date: 'Nov 2023',
    link: 'https://gamma.app/',
  },
  {
    position: 'Full Stack Engineer',
    company: 'Yellow Systems ',
    logo: '/images/careers/Yellow.png',
    location: 'United States',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Jul 2019',
    end_date: 'Mar 2022',
    link: 'https://yellow.systems',
  },
  {
    position: 'Full Stack Engineer',
    company: 'Adobe',
    logo: '/images/careers/Adobe.png',
    location: 'United States',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: 'Mar 2017',
    end_date: 'June 2019',
    link: 'https://adobe.com',
  },
  {
    position: 'Frontend Developer',
    company: 'Code Ninjia',
    logo: '/images/careers/Ninjia.png',
    location: 'Canada',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: 'Mar 2017',
    end_date: 'June 2019',
    link: 'https://www.codeninjaconsulting.com/',
  },
  {
    position: '',
    company: 'App Academy',
    logo: '/images/careers/App.png',
    location: '',
    location_type: '',
    type: '',
    start_date: 'Jan 2022',
    end_date: 'Dec 2022',
    link: 'http://www.appacademy.io',
  },
  {
    position: "Bachelor's Degree",
    company: 'Stanford University',
    logo: '/images/careers/Univ.jpg',
    location: '',
    location_type: '',
    type: '',
    start_date: 'Oct 2011',
    end_date: 'Oct 2015',
    link: 'http://stanford.edu',
  },
];
